- include_vars: ../jenkins_master/defaults/my_var.yml

- name: upgrade all packages
  yum: name=* state=latest

- name: Removing Old Java_1.7 version
  yum:
    name: java-1.7.0
    state: absent

- name: Installing some rpm packages
  yum:
    name: "{{item}}"
    state: present
    enablerepo: epel
  with_items:
        - git
        - java-1.8.0
        - ansible
        - docker
        - curl

#IMP Verify latest LTS repo url from https://pkg.jenkins.io/redhat/
- name: Copying Jenkins LTS repo
  get_url:
     url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
     dest: /etc/yum.repos.d/

#IMP Verify latest gpg key url from https://pkg.jenkins.io/redhat/ 
- name: Adding the repository gpg keys
  rpm_key:
     key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
     #key: https://jenkins-ci.org/redhat/jenkins-ci.org.key
     state: present

## Configure Jenkins master
- name: Stop jenkins Master Service
  service:
    name: jenkins
    state: stopped
  ignore_errors: yes

- name:  Checking jenkins master version
  shell: "rpm -q jenkins-{{jenkins_version}}"
  register: result1
  ignore_errors: yes

- name: Remove jenkins version
  yum:
    name: "jenkins"
    state: absent
  register: result2
  when:
        - result1.rc == 1
  #when: (result1.find('not installed') != -1)

- name: Remove previous jenkins home data
  file: 
    path: "/var/lib/jenkins"
    state: absent
  when: ( result1.rc == 1 )
#  when:
#        - result2.rc == 0

- name: Installing Jenkins Entered TLS stable Veriosn
  yum:
    name: "jenkins-{{jenkins_version}}"
    state: present
  when: ( result1.rc == 1 )


- name: Assigning shell to jenkins user
  user:
    name: jenkins
    shell: /bin/bash

- name: Copying Jenkins Skell file in jenkins users home dir
  shell: "cp /etc/skel/.bash* /var/lib/jenkins"

- file:
    path: "{{ jenkins_home }}/.ssh"
    mode: 0700
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory

- file:
    path: "{{ jenkins_home }}/plugins"
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory

- name: Add user Public Key
  copy: 
     src: "../jenkins_master/files/jenkins_id_rsa.pub"
     dest: "{{ jenkins_home }}/.ssh/id_rsa.pub"
     mode: 0644
     owner: "{{ username }}"
     group: "{{ username }}"
#  when: ( result1.rc == 1 )

- name: Add user Private Key
  copy: 
     src: "../jenkins_master/files/jenkins_id_rsa"
     dest: "{{ jenkins_home }}/.ssh/id_rsa"
     mode: 0600
     owner: "{{ username }}"
     group: "{{ username }}"
#  when: ( result1.rc == 1 )

- name: Adding Bitbucket Public Key
  copy: 
     src: "../jenkins_master/files/bitbucket_pub"
     dest: "{{ jenkins_home }}/.ssh/known_hosts"
     mode: 0644
     owner: "{{ username }}"
     group: "{{ username }}"
  when: ( result1.rc == 1 )


- name: git config user name
  shell: git config --global user.name "{{ git_name }}" executable=/bin/bash
  become: yes
  become_user: "{{ username }}"

- name: git config user email
  shell: git config --global user.email "{{ git_email }}" executable=/bin/bash
  become: yes
  become_user: "{{ username }}"

- name: sleep for 30 seconds and continue with play
  wait_for: timeout=30
  delegate_to: localhost

- name: Pull Jenkins Configuration from bitbuket
  git:
    repo: "{{ jenkins_bucket_url }}"
    dest: "{{ jenkins_bucket }}"
    accept_hostkey: yes
    force: yes
  become: yes
  become_user: "{{ username }}"

- name: copying jobs and plugin from repo to jenkins home
  shell: "cp -frv {{ jenkins_bucket }}/* /var/lib/jenkins/ ; chown  jenkins.jenkins -R /var/lib/jenkins/"

#- name: Removing Old plugins if Jenkins version changed
- name: "Will Updated new plugins if Jenkins Version NOT changed - {{jenkins_plug_url}}"
  shell: "cd {{  jenkins_home }}/plugins;if [ -f {{item}} ];then echo ;else wget {{jenkins_plug_url}}/{{item}};fi"
  with_items: "{{ jenkins_plugins }}"
  when: ( result1.rc == 0 )
  ignore_errors: yes

### // Add plugin name here my_var.yml to install on jenkins // ###
- name: "Get other New plugins from Internet if Jenkins Version changed - JenkinsVersion: {{jenkins_version}}"
  get_url: 
   url: "{{jenkins_plug_url}}/{{item}}"
   dest: "{{  jenkins_home }}/plugins"
  with_items: "{{ jenkins_plugins }}"
  when: ( result1.rc == 1 )

## Adding Custome plugin and config data
- name: Adding Custome plugin and config data
  git:
    repo: "{{ jenkins_data_bucket_url }}"
    dest: "{{ jenkins_data_bucket }}"
    accept_hostkey: yes
    force: yes
  become: yes
  become_user: "{{ username }}"

- name: copying Custome plugin and config data
  shell: "cp -frv {{ jenkins_data_bucket }}/jenkins-plugins/* {{  jenkins_home }}/plugins; cp -frv {{ jenkins_data_bucket }}/jenkins-config/* {{  jenkins_home }}"

- name: Chaning User and Group Owner "{{ username }}"
  shell: "chown  jenkins.jenkins -R /var/lib/jenkins/"

## Checking Previous AMI Name
- name: "Checking Previous Slave AMI Name"
  shell: "grep ami- {{config_xml}}|tr '>' ' '|tr '<' ' '|awk '{print $2}'"
  register: old_ami

- name: "Replacing new Slave AMI: {{slave_ami}}"
  replace:
    path: "{{config_xml}}"
    regexp: '{{old_ami.stdout}}'
    replace: '{{slave_ami}}'
    backup: yes

## Checking Previous Slave SubnetID
- name: "Checking Previous Slave SubnetID"
  shell: "grep subnet- {{config_xml}}|tr '>' ' '|tr '<' ' '|awk '{print $2}'"
  register: old_subnet

- name: "Replacing new SubnetID: {{slave_subnet}}"
  replace:
    path: "{{config_xml}}"
    regexp: '{{old_subnet.stdout}}'
    replace: '{{slave_subnet}}'
    backup: yes

## Checking Previous Slave Security Group
- name: "Checking Previous Slave ecurity Group"
  shell: "grep '<securityGroups>' {{config_xml}}|tr '>' ' '|tr '<' ' '|awk '{print $2}'"
  register: old_sg

- name: "Replacing new Slave Security Group: {{slave_sg}}"
  replace:
    path: "{{config_xml}}"
    regexp: '{{old_sg.stdout}}'
    replace: '{{slave_sg}}'
    backup: yes

## Checking Previous Slave IAM Role
- name: "Checking Previous Slave IAM Role"
  shell: "grep '<iamInstanceProfile>' {{config_xml}}|tr '>' ' '|tr '<' ' '|awk '{print $2}'"
  register: old_iam

- name: "Replacing new Slave IAM Role: {{slave_iam}}"
  replace:
    path: "{{config_xml}}"
    regexp: '{{old_iam.stdout}}'
    replace: '{{slave_iam}}'
    backup: yes

## Checking Previous Slave Slave Tag name
- name: "Checking Previous Slave Tag name"
  shell: "grep '<value>' {{config_xml}}|tr '>' ' '|tr '<' ' '|awk '{print $2}'"
  register: old_tag

- name: "Replacing new Slave Tag name: {{slave_tag}}"
  replace:
    path: "{{config_xml}}"
    regexp: '{{old_tag.stdout}}'
    replace: '{{slave_tag}}'
    backup: yes

## Replacing SMTP setup for bitbucket commit.
##Check below JENKINS_JAVA_OPTIONS in line: option and compare with original file except content part -Dhudson.tasks.MailSender.SEND_TO_USERS_WITHOUT_READ=true
- name: Checking jenkins smtp java option main config file
  shell: "grep -e {{jenkins_java_smtp_option}} {{jenkins_config}}"
  ignore_errors: yes
  register: smtp_result

- name: Replacing new JENKINS_JAVA_OPTIONS
  replace:
    path: "{{jenkins_config}}"
    regexp: '(\s+JENKINS_JAVA_OPTIONS=.*)(")$'
    replace: '\1 {{jenkins_java_smtp_option}}\2'
    backup: yes
  when:
        - smtp_result.rc == 1

- name: Start and Enabled jenkins Master Service
  service:
    name: jenkins
    #state: started
    enabled: no
